# BTC代币数据获取系统配置文件
# 支持获取BTC、ETH、KAS、BNB等代币的价格、供应量和算力数据

# API密钥配置
api_keys:
  # Etherscan API密钥 - 用于获取ETH相关数据和多链余额查询
  # 获取地址: https://etherscan.io/apis
  etherscan: "U6GXWFS91WK8XG3XH4DCWVVTN24N35HW92"

# 缓存系统配置
cache:
  # 是否启用缓存功能
  # true: 启用缓存，提高响应速度，减少API调用
  # false: 禁用缓存，每次都从API获取最新数据
  enabled: true
  
  # 缓存有效期（分钟）
  # 超过此时间的缓存数据将被视为过期并重新获取
  # 建议值: 5-60分钟，根据对数据实时性的要求调整
  duration_minutes: 5
  
  # SQLite数据库文件路径（相对于项目根目录）
  # 系统会自动创建数据库文件和表结构
  database: "cache/token_cache.db"

# API请求配置
api:
  # API请求间隔时间（秒）
  # 用于控制请求频率，防止触发API服务商的速率限制
  # 建议值: 1-3秒
  request_delay: 2
  
  # HTTP请求超时时间（秒）
  # 请求超过此时间将被取消
  # 建议值: 5-15秒，根据网络环境调整
  timeout: 10

# 支持的代币列表
# 系统将按此列表获取代币数据
# 目前支持的所有币种（共11种）
tokens:
  # 主流币种
  - BTC   # 比特币 - 支持价格、供应量、算力 (POW)
  - ETH   # 以太坊 - 支持价格、供应量 (POS，无算力)
  - BNB   # 币安币 - 支持价格、供应量 (POS，无算力)
  
  # 新兴项目
  - KAS   # Kaspa  - 支持价格、供应量、算力 (POW)
  - SOL   # Solana - 支持价格、供应量 (POS，无算力)
  - AVAX  # Avalanche - 支持价格、供应量 (POS，无算力)
  - MATIC # Polygon - 支持价格、供应量 (POS，无算力)
  
  # 经典币种
  - LTC   # 莱特币 - 支持价格、供应量 (POW，但当前API可能无算力数据)
  - DOGE  # 狗狗币 - 支持价格、供应量 (POW，但当前API可能无算力数据)
  
  # 二层网络
  - ARB   # Arbitrum - 支持价格、供应量 (Layer2，无算力)
  - OP    # Optimism - 支持价格、供应量 (Layer2，无算力)

# 测试用配置 - 如果只想测试部分币种，可以使用以下配置
# tokens:
#   - BTC
#   - ETH
#   - KAS

# 数据源配置
data_sources:
  # 价格数据源 - CoinGecko免费API
  price_api: "https://api.coingecko.com/api/v3"
  
  # 汇率数据源 - 获取USD到CNY汇率
  exchange_rate_api: "https://api.exchangerate-api.com/v4/latest/USD"
  
  # 区块链数据源
  blockchain:
    btc: "https://api.blockchain.info/stats"     # BTC算力数据
    kas: "https://api.kaspa.org/info/hashrate"   # KAS算力数据
    eth: "https://api.etherscan.io/api"          # ETH供应量数据
