# BTC代币数据获取系统配置文件模板
# 支持获取BTC、ETH、KAS、BNB等代币的价格、供应量和算力数据
# 
# 使用说明：
# 1. 复制此文件为 config.yaml
# 2. 将 YOUR_API_KEY_HERE 替换为您的真实API密钥
# 3. 根据需要调整其他配置参数

# API密钥配置
api_keys:
  # Etherscan API密钥 - 用于获取ETH相关数据和多链余额查询
  # 获取地址: https://etherscan.io/apis
  # ⚠️ 请将下面的 YOUR_ETHERSCAN_API_KEY_HERE 替换为您的真实API密钥
  etherscan: "YOUR_ETHERSCAN_API_KEY_HERE"
  
  # 其他API密钥（如需要）
  # coingecko: "YOUR_COINGECKO_API_KEY_HERE"
  # binance: "YOUR_BINANCE_API_KEY_HERE"

# 缓存系统配置
cache:
  # 是否启用缓存功能
  # true: 启用缓存，提高响应速度，减少API调用
  # false: 禁用缓存，每次都从API获取最新数据
  enabled: true
  
  # 缓存有效期（分钟）
  # 超过此时间的缓存数据将被视为过期并重新获取
  # 建议值: 5-60分钟，根据对数据实时性的要求调整
  duration_minutes: 5
  
  # SQLite数据库文件路径（相对于项目根目录）
  # 系统会自动创建数据库文件和表结构
  database: "cache/token_cache.db"

# API请求配置
api:
  # API请求间隔时间（秒）
  # 用于控制请求频率，防止触发API服务商的速率限制
  # 建议值: 1-3秒
  request_delay: 2
  
  # HTTP请求超时时间（秒）
  # 请求超过此时间将被取消
  # 建议值: 5-15秒，根据网络环境调整
  timeout: 10

# 支持的代币列表
# 系统将按此列表获取代币数据
# 目前支持的所有币种（共11种）
tokens:
  # 主流币种
  - BTC   # 比特币 - 支持价格、供应量、算力 (POW)
  - ETH   # 以太坊 - 支持价格、供应量 (POS，无算力)
  - BNB   # 币安币 - 支持价格、供应量 (POS，无算力)
  
  # 新兴项目
  - KAS   # Kaspa  - 支持价格、供应量、算力 (POW)
  - SOL   # Solana - 支持价格、供应量 (POS，无算力)
  - AVAX  # Avalanche - 支持价格、供应量 (POS，无算力)
  - MATIC # Polygon - 支持价格、供应量 (POS，无算力)
  - LTC   # Litecoin - 支持价格、供应量、算力 (POW)
  - DOGE  # Dogecoin - 支持价格、供应量、算力 (POW)
  - ARB   # Arbitrum - 支持价格、供应量 (Layer2，无算力)
  - OP    # Optimism - 支持价格、供应量 (Layer2，无算力)

# 数据格式配置
display:
  # 货币显示格式
  currency:
    # 主要货币（美元）
    primary: "USD"
    
    # 次要货币（人民币）
    secondary: "CNY"
    
    # 汇率（USD to CNY，可定期更新）
    exchange_rate: 7.2

# 日志配置
logging:
  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  
  # 是否启用文件日志
  file_enabled: false
  
  # 日志文件路径
  file_path: "logs/system.log"
